/* ============================================================
   MALAY GROUP — brand identity data for six separate experiences
   Malay Restaurant = primary/flagship; five secondary concepts.
   Factual base: company dossier + MALY portfolio menu workbook.
   ============================================================ */
(function () {
  window.MALY_BRANDS = {
    'malay-restaurant': {
      num: '01',
      slug: 'malay-restaurant',
      key: 'malay',
      name: 'Malay Restaurant',
      short: 'Malay',
      mark: 'MR',
      logo: 'assets/logo.png',
      hasLogo: true,
      accent: '#C9A86A',
      accent2: '#E9CF96',
      ink: '#F4EBDD',
      positioning: 'Heritage Malay & Asian Dining',
      tagline: 'A Legacy of Food. A Future of Flavour.',
      story: 'The heritage flagship of the wider culinary portfolio associated with Malay Fast Foods. Malay, Sri Lankan, Chinese, Indian and Arabic flavours, carried forward by the generations.',
      points: ['Heritage recipes passed down through generations', 'Five great culinary traditions in one kitchen', 'Dine-in, takeaway and delivery from the heart of Dehiwala'],
      menuKey: 'Malay Restaurant',
      menuLead: 'The full Malay Restaurant menu \u2014 from Rasa Sayang noodles and the kottu corner to rice dishes, Malay specials and handcrafted drinks.',
      dine: ['Dine-in', 'Takeaway', 'Delivery'],
      orderNote: 'Order online at malayrestaurant.appigo.co',
      orderUrl: 'https://malayrestaurant.appigo.co',
      address: '115 Hill Street, Dehiwala 10350',
      dishTags: ['MALAY SPECIAL', 'CHEF RECOMMENDED', 'KOTTU CORNER'],
      heroNote: 'Signature heritage plate \u2014 Malay-style dum biryani. Inspired by real menu favourites, photographed for the brand.'
    },
    'cafe-asiana': {
      num: '02',
      slug: 'cafe-asiana',
      key: 'asiana',
      name: 'Cafe Asiana',
      short: 'Asiana',
      mark: 'CA',
      logo: '',
      hasLogo: false,
      accent: '#8FA982',
      accent2: '#C3D6BA',
      ink: '#F4F7F1',
      positioning: 'Contemporary Asian Dining',
      tagline: 'Modern Asia, made to order.',
      story: 'A contemporary take on pan-Asian dining \u2014 Singapore-style noodles, fried rice, nasi goreng, seafood, wraps and soups. Fast, fresh and boldly flavoured.',
      points: ['Pan-Asian menu from noodles to nasi goreng', 'Fresh seafood and lively wok cooking', 'Contemporary dining with delivery'],
      menuKey: 'Cafe Asiana',
      menuLead: 'A pan-Asian menu spanning drinks, across fried rice, noodles, seafood, wraps and soups.',
      dine: ['Dine-in', 'Takeaway', 'Delivery'],
      orderNote: 'Order through the group line +94 11 777 7999',
      orderUrl: 'tel:+94117777999',
      address: 'Part of the wider Malay Fast Foods portfolio',
      dishTags: ['ASIAN FUSION', 'WOK FRESH', 'SEAFOOD'],
      heroNote: 'Wok-charred noodles and vibrant pan-Asian plates.'
    },
    'shanghai-wok': {
      num: '03',
      slug: 'shanghai-wok',
      key: 'shanghai',
      name: 'Shanghai Wok',
      short: 'Shanghai',
      mark: 'SW',
      logo: '',
      hasLogo: false,
      accent: '#B4573A',
      accent2: '#E8B08F',
      ink: '#FBF0EA',
      positioning: 'Fast-Casual Chinese',
      tagline: 'Big wok flavours, made quick.',
      story: 'Fast-casual Chinese done right \u2014 fried rice, noodles, chop suey and chilli dishes from a hot, honest wok. Built for delivery and speed.',
      points: ['Wok-fired fried rice, noodles and chop suey', 'Fresh chilli dishes with real heat', 'Quick, delivery-friendly service'],
      menuKey: 'Shanghai Wok',
      menuLead: 'A tight, quick-fire Chinese menu \u2014 perfect for lunch, dinner or delivery.',
      dine: ['Takeaway', 'Delivery'],
      orderNote: 'Order through the group line +94 11 777 7999',
      orderUrl: 'tel:+94117777999',
      address: 'Part of the wider Malay Fast Foods portfolio',
      dishTags: ['FAST CASUAL', 'WOK FRESH', 'CHILLI HEAT'],
      heroNote: 'Sizzling wok energy \u2014 noodles, rice and chilli.'
    },
    'nelum-flower': {
      num: '04',
      slug: 'nelum-flower',
      key: 'nelum',
      name: 'Nelum Flower',
      short: 'Nelum',
      mark: 'NF',
      logo: '',
      hasLogo: false,
      accent: '#6B7F9E',
      accent2: '#AEC0D6',
      ink: '#F0F4F9',
      positioning: 'Everyday Sri Lankan Cuisine',
      tagline: 'Comfort, cooked the Sri Lankan way.',
      story: 'Everyday Sri Lankan food \u2014 rice & curry, kottu, and fresh juices, served the warm, homely way. A daily staple for every occasion.',
      points: ['Rice & curry, kottu and hoppers daily', 'Fresh juices to start or finish the day', 'Warm, family-friendly dining'],
      menuKey: 'Nelum Flower',
      menuLead: 'Everyday Sri Lankan plates \u2014 from rice & curry to kottu and fresh juices.',
      dine: ['Dine-in', 'Takeaway', 'Delivery'],
      orderNote: 'Order through the group line +94 11 777 7999',
      orderUrl: 'tel:+94117777999',
      address: 'Part of the wider Malay Fast Foods portfolio',
      dishTags: ['SRI LANKAN CLASSIC', 'DAILY STAPLE', 'FRESH JUICES'],
      heroNote: 'Rice & curry warmth \u2014 the everyday Sri Lankan table.'
    },
    'pakistan-darbar': {
      num: '05',
      slug: 'pakistan-darbar',
      key: 'pdarbar',
      name: 'Pakistan Darbar',
      short: 'Pakistan Darbar',
      mark: 'PD',
      logo: 'assets/brand-pakistan-darbar.png',
      hasLogo: true,
      accent: '#7C6A9E',
      accent2: '#B9A9D4',
      ink: '#F5F1FA',
      positioning: 'Pakistani BBQ / Biryani / Arabic',
      tagline: 'Charcoal fire, bold flavour.',
      story: 'Rich Pakistani and Arabic flavours \u2014 charcoal BBQ, biryani, kabsa, kababs and shaorma, built around fire, spice and generous portions.',
      points: ['Charcoal BBQ and kababs', 'Biryani, kabsa and shaorma', 'Bold Pakistani and Arabic spicing'],
      menuKey: 'Pakistan Darbar',
      menuLead: 'Menu on request. The kitchen builds rich BBQ, biryani and Arabic spreads for dine-in and catering.',
      dine: ['Dine-in', 'Takeaway', 'Catering'],
      orderNote: 'Enquire through the group line +94 11 777 7999',
      orderUrl: 'tel:+94117777999',
      address: 'Part of the wider Malay Fast Foods portfolio',
      dishTags: ['CHARCOAL BBQ', 'BIRYANI', 'KABABS'],
      heroNote: 'Charcoal smoke, kababs and biryani. Menu prepared on request.'
    },
    'darbar-biryani-bbq': {
      num: '06',
      slug: 'darbar-biryani-bbq',
      key: 'darbar',
      name: 'Darbar Biryani & BBQ',
      short: 'Darbar',
      mark: 'DB',
      logo: '',
      hasLogo: false,
      accent: '#A8864E',
      accent2: '#D9BD7F',
      ink: '#F9F4E8',
      positioning: 'Biryani + BBQ Specialist',
      tagline: 'One plate, cooked slow. One grill, fired loud.',
      story: 'A focused biryani and barbecue kitchen \u2014 fragrant dum-cooked biryani and fire-kissed BBQ, built for family meals, big portions and catering.',
      points: ['Slow dum-cooked biryani', 'Charcoal BBQ and large-format portions', 'Built for family meals & catering'],
      menuKey: 'Darbar Biryani & BBQ',
      menuLead: 'Menu on request. Specialised biryani and BBQ spreads for families and events.',
      dine: ['Takeaway', 'Delivery', 'Catering'],
      orderNote: 'Enquire through the group line +94 11 777 7999',
      orderUrl: 'tel:+94117777999',
      address: 'Part of the wider Malay Fast Foods portfolio',
      dishTags: ['DUM BIRYANI', 'CHARCOAL BBQ', 'FAMILY MEALS'],
      heroNote: 'Dum biryani and charcoal BBQ \u2014 restaurant-sized, family-ready.'
    }
  };

  window.MALY_BRAND_LIST = Object.keys(window.MALY_BRANDS).map(function (k) { return window.MALY_BRANDS[k]; });
  window.CYRB_brandSlug = function (b) { return { malay: 'malay-restaurant', asiana: 'cafe-asiana', shanghai: 'shanghai-wok', nelum: 'nelum-flower', pdarbar: 'pakistan-darbar', darbar: 'darbar-biryani-bbq' }[b] || 'malay-restaurant'; };
})();